# 全局代理开关
proxy:
  enabled: true
  url: "socks5://127.0.0.1:10808"


headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
  Cookie: "vote=1; country=TW; blacklisted_tags=%5B%22%22%5D; konachan.com=BAh7B0kiD3Nlc3Npb25faWQGOgZFVEkiJWZjZWQzOWEzYzQ3MWJjOTFjODIzMjY0ZTRhNTYxNTQ3BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMXVvWUtuT1RNNXg1VkVaRWs4ajY1V0lSWGUxK0prb0w1TjF6U1EvVVFtcWM9BjsARg%3D%3D--684c4b1adfd3224c7ec7615a0a52861a527ee754; reported_error=1; forum_post_last_read_at=%222024-02-11T10%3A21%3A26%2B01%3A00%22
"

#单独代理开关
#proxies_v2ray:
#  enabled: true
#  http: "socks5://127.0.0.1:10808"
#  https: "socks5://127.0.0.1:10808"
#
#proxies_ssr:
#  enabled: false
#  http: "socks5://127.0.0.1:10807"
#  https: "socks5://127.0.0.1:10807"

# Konachan相关配置(domain设置为net不需要代理，com需要代理)
konachan:
  rating:
    - s # s:Safe only
    - q # q: Questionable only (Ecchi)
#    - e # e: Explicit only (Hentai)
  domain: com
  size: file_url # file_url 是原图 | jpeg_url 是小图