# 全局代理开关
proxy:
  enabled: true
  url: "http://127.0.0.1:10809"


headers:
  User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
  Cookie: "cf_clearance=WselsHTlG7k5c7.yNsk_RJuOu8SLdt2UBItEDS_4zYs-1710388735-1.0.1.1-tnkF8ae51rhiLDsdjXXJfhBnnD1cIjfGhE2x0rXL6YcyQwcAawvqZhvS0IoRbn.68oCQQjp81Z1HbbYzT5fFcg; vote=1; country=TW; reported_error=1; login=inory; pass_hash=0822e999899c1e035f32f460373e6bf6b329bbee; forum_post_last_read_at=%221960-01-01T00%3A00%3A00.000Z%22; user_id=278823; user_info=278823%3B20%3B0; has_mail=0; comments_updated=0; block_reason=; resize_image=1; show_advanced_editing=1; my_tags=; blacklisted_tags=%5B%5D; held_post_count=0; konachan.com=BAh7CEkiD3Nlc3Npb25faWQGOgZFVEkiJWUwM2QxODkwYzZjNmYyOTk4YmU3OTc1ZTFlMzhhZTk1BjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMVB2VVdJMlI4Um5wLzNvWCtVYnlzVXd5YnhuUDRBNXM1Sk53RFcyc3E3WEE9BjsARkkiDHVzZXJfaWQGOwBGaQMnQQQ%3D--5b05addf22a78225fdfb342a8ec5f8d8cc343e8c
"

#单独代理开关
#proxies_v2ray:
#  enabled: true
#  http: "socks5://127.0.0.1:10808"
#  https: "socks5://127.0.0.1:10808"
#
#proxies_ssr:
#  enabled: false
#  http: "socks5://127.0.0.1:10807"
#  https: "socks5://127.0.0.1:10807"

# Konachan相关配置(domain设置为net不需要代理，com需要代理)
konachan:
  rating:
    - s # s:Safe only
    # - q # q: Questionable only (Ecchi)
    # - e # e: Explicit only (Hentai)
  domain: com
  size: file_url # file_url 是原图 | jpeg_url 是小图